version: 2
updates:
  - package-ecosystem: "npm"
    directories: ["/src"]
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directories: ["/"]
    schedule:
      interval: "monthly"
