version: 2
updates:
  - package-ecosystem: "npm"
    directories: ["/"]
    schedule:
      interval: "weekly"
    groups:
      dev-dependencies:
        dependency-type: "development"
  - package-ecosystem: "github-actions"
    directories: ["/"]
    schedule:
      interval: "monthly"
